### ISSUE TITLE
Eigene Ansagen als Text, Sprache/Stimme im Request mitgeben

### ISSUE THREAD

**Issue by webgreat** [Placetel/call-control-notify-api#10]
Ein mega Feature wäre die Möglichkeit eigene Ansagen (forward_announcement ) nicht als ID mitzugeben sondern als Text mit der Ausgabestimme/Sprache. 

Somit könnte man den Anrufenden mit Namen ansprechen oder weitere Informationen ausgeben. 

Frage: Die ID die hier angegeben wird, findet man die im Backend? Ich sehe da nichts außer über den Quelltext zu gehen.

**Comment by kangguru** [comment]
Das klingt wirklich nach einem interessanten Usecase, den wir sogar schon einmal intern diskutiert haben. Vermutlich wird eine Umsetzung aufgrund von zu hohen Latenzen in der Synthesize API scheitern. Falls sich hier Neuigkeiten ergeben halten wir Sie gern auf dem Laufenden.

Bezüglich der Ansage ID, diese können Sie über den `getPrompts` Endpunkt auslesen.

```
curl https://api.placetel.de/api/getPrompts.json
```

**Comment by webgreat** [comment]
Moin @kangguru wie wäre es dann Audio Files per Api zu senden? Als Alternative

**Comment by felixtriller** [comment]
@webgreat das funktioniert in unserem Stack Stand heute leider auch nicht.

Ich schreibe es nochmal auf unsere Feature-Liste und würde das Ticket dann erstmal schließen.
