### ISSUE TITLE
Ausgehende Anrufe

### ISSUE THREAD

**Issue by cklm** [Placetel/call-control-notify-api#4]
Hallo, 
wäre es auch möglich, für ausgehende Calls einen Webhook aufzurufen?
Es müsste eigentlich nur ein weiteres Event `IncomingCall` geben, sowie die beiden Events `CallAccepted` und `HungUp` für ausgehende Anrufe getriggert werden. Habt ihr sowas in Planung oder Umsetzung?

**Comment by GunnarLieb** [comment]
Das würde uns auch interessieren.

**Comment by felixtriller** [comment]
Hallo @cklm @GunnarLieb an einem Event für ausgehende Calls arbeiten wir gerade! Ich kann leider noch nicht genau sagen, wann wir fertig sind.

**Comment by cklm** [comment]
hi @felixtriller danke für die Info!
Kannst du uns einen ungefähren Zeithorizont geben? Sind das eher zwei Wochen oder zwei Monate?
Ich hätte nämlich einen Kunden mit mittelfristig 50 Nebenstellen der gerne zu Placetel wechseln würde - Voraussetzung wäre aber die API für ausgehende Anrufe.
Stelle mich auch gerne als Betatester zur Verfügung :)

**Comment by felixtriller** [comment]
Hi @cklm,

einen genaueren Zeitpunkt kann ich dir leider noch nicht sagen, in diesem Jahr wird es aber wohl nichts mehr, eher Januar. Dann würden wir aber gerne fürs Beta-Testing auf dich zurück kommen!

**Comment by christophbue** [comment]
Hallo @felixtriller,
wir sind auch ganz stark an Benachrichtigungen für ausgehende Anrufe interessiert (für unser Cloud CTI Produkt PhoneMondo). 
Kannst du mich bitte mit auf die Beta-Liste setzen?
Danke!

**Comment by felixtriller** [comment]
@christophbue ist notiert!

**Comment by cklm** [comment]
Hi @felixtriller, 

gibts hier etwas neues? Stehen gerne als Tester zur Verfügung, sobald ihr etwas habt :)

**Comment by webgreat** [comment]
Das würde mich auch interessieren!

**Comment by webgreat** [comment]
Eine Ansage ob/wie/wann/ob überhaupt wäre schon wünschenswert.

**Comment by mpdude** [comment]
👋🏻 Ebenfalls interessiert, gerne auch als Versuchskaninchen.

**Comment by mpdude** [comment]
Gibt es generell einen Kanal, um solche Wünsche anzubringen, ein Nutzerforum oder ähnliches?

Habe das Gefühl, dass Wünsche oder Vorschläge an der Hotline/Helpdesk abperlen...

**Comment by JulianHi** [comment]
Wir sind auch interessiert und würden gerne beim Beta Test teilnehmen.

**Comment by webgreat** [comment]
@felixtriller ?

**Comment by pstaender** [comment]
Wir arbeiten an einer Implementierung können aber z.Zt. noch keine Angaben zu einem Zeitpunkt geben.

**Comment by mpdude** [comment]
Bis dahin: snom Telefone können ggf eine Action URL für abgehende Gespräche aufrufen.

**Comment by nformsven** [comment]
Wir haben für unser hauseigenes ERP System eine CTI API programmiert und sind ebenfalls an diesem Feature interessiert.

**Comment by tobiashieb** [comment]
Liebes Placetel Team,

wie sieht es denn mit diesem Thema aus? Wir würden euch gern in TeamGrid integrieren - sehen das aber als Grundvoraussetzung.

Danke,
Tobias

**Comment by patrick-goeCommerce** [comment]
Wir evaluieren gerade Teamgrid und möchten unsere Placetel Telefonanlage integrieren. Wann wird dieses Feature umgesetzt?

**Comment by nformsven** [comment]
@felixtriller Können wir als Placetel-Kunde mitlerweile davon ausgehen, dass eine Umsetzung nicht mehr geplant ist?

**Comment by Cloudkasten** [comment]
Das würde mich auch sehr interssieren - ist das Thema noch aktuell?

**Comment by jdaehne** [comment]
Gibt es hierzu mittlerweile ein Feedback? Ist dies in naher Zukunft geplant?

**Comment by felixtriller** [comment]
Ist für einen kleinen Teil unserer Kunden jetzt online, im Laufe der Woche dann für die komplette Plattform. Die Dokumentation ist angepasst.

Sorry, dass es so lange gedauert hat 💐

**Comment by ZuSe** [comment]
Super, habe es eben getestet.
Wäre es u.a. auch möglich, dass neben der internen ID (@fbpx.de) auch die verwendete Rufnummer für den call mitgegeben wird? Damit wissen wir dann im System mit was uns auch der Gegenüber sieht.

**Comment by webgreat** [comment]
Die UID und Nummer kannst du doch über die API abrufen ... https://api.placetel.de/api/getVoIPUsers

**Comment by yoyostile** [comment]
> Die UID und Nummer kannst du doch über die API abrufen ... https://api.placetel.de/api/getVoIPUsers

Oder auch in unserer gut versteckten V2 API: https://api.placetel.de/v2/docs/#fetch-a-sip-user :)

**Comment by felixtriller** [comment]
Ich mache das Ticket dann mal zu :)
