### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by GunnarLieb** [Placetel/call-control-notify-api#5]
Hallo @felixtriller,

ich hatte vor einiger Zeit einen PR für eine Coldfusion Implementierung gemacht, der ist immer noch offen. Bitte annehmen oder ablehnen.

**Comment by felixtriller** [comment]
Hi @GunnarLieb, ist der PR denn so vollständig? Ich verstehe den auskommentierten Teil nicht so ganz.
