### ISSUE TITLE
setting up NEW telephone numbers

### ISSUE THREAD

**Issue by ghost** [Placetel/call-control-notify-api#6]
From what i can see this API does not allow setting up new telephone numbers ?
In Germany you need to provide Proof of Address.
I need to setup 100's of numbers for my clients.

I think i need:
1. Way to search for telephone numbers by postcoe or telephone number prefix.
2. Once a number is selected a way to send in the Residnet address scan image
3. Call abck that everything is ok and new number is activated.

I will write my code in golang and can make a pull request when done if you want it.

**Comment by felixtriller** [comment]
@ghost this API is for notifying calls. Setting up phone numbers programmatically due to the restrictions of the BNetzA, as you already mentioned.
